import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { sassPlugin } from "esbuild-sass-plugin";
import fs from "fs";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv.includes("production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  metafile: true,
  bundle: true,
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts", "src/ui/styles/styles.scss"],
  entryNames: "[name]",
  outdir: ".",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },

  minify: prod,
  minifyWhitespace: prod,
  minifyIdentifiers: prod,
  minifySyntax: prod,
  plugins: [
    sassPlugin({
      type: "css",
      style: "compressed",
    }),
  ],
});

if (prod) {
  const result = await context.rebuild();

  fs.writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
  process.exit(0);
} else if (watch) {
  await context.watch(); // Watch for file changes in dev mode (npm run dev)
} else {
  await context.rebuild(); // One-shot dev build (reload.sh)
  process.exit(0);
}